// This is a placeholder for the IDL that would be generated by Anchor
// In a real project, you would run 'anchor build' and the IDL would be generated automatically

export const IDL = {
  "version": "0.1.0",
  "name": "privax_protocol",
  "instructions": [
    {
      "name": "initialize",
      "accounts": [
        {
          "name": "programState",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "admin",
          "isMut": true,
          "isSigner": true
        },
        {
          "name": "systemProgram",
          "isMut": false,
          "isSigner": false
        }
      ],
      "args": [
        {
          "name": "tokenMintAddress",
          "type": "publicKey"
        },
        {
          "name": "verifierProgramId",
          "type": "publicKey"
        }
      ]
    },
    {
      "name": "addRelayer",
      "accounts": [
        {
          "name": "programState",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "admin",
          "isMut": false,
          "isSigner": true
        }
      ],
      "args": [
        {
          "name": "relayerAddress",
          "type": "publicKey"
        }
      ]
    },
    {
      "name": "removeRelayer",
      "accounts": [
        {
          "name": "programState",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "admin",
          "isMut": false,
          "isSigner": true
        }
      ],
      "args": [
        {
          "name": "relayerAddress",
          "type": "publicKey"
        }
      ]
    },
    {
      "name": "transferOwnership",
      "accounts": [
        {
          "name": "programState",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "admin",
          "isMut": false,
          "isSigner": true
        }
      ],
      "args": [
        {
          "name": "newAdmin",
          "type": "publicKey"
        }
      ]
    },
    {
      "name": "deposit",
      "accounts": [
        {
          "name": "programState",
          "isMut": false,
          "isSigner": false
        },
        {
          "name": "user",
          "isMut": true,
          "isSigner": true
        },
        {
          "name": "userTokenAccount",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "programTokenVault",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "programTokenVaultAuthority",
          "isMut": false,
          "isSigner": false
        },
        {
          "name": "tokenProgram",
          "isMut": false,
          "isSigner": false
        },
        {
          "name": "systemProgram",
          "isMut": false,
          "isSigner": false
        },
        {
          "name": "rent",
          "isMut": false,
          "isSigner": false
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        },
        {
          "name": "commitment",
          "type": {
            "array": ["u8", 32]
          }
        }
      ]
    },
    {
      "name": "withdraw",
      "accounts": [
        {
          "name": "programState",
          "isMut": false,
          "isSigner": false
        },
        {
          "name": "user",
          "isMut": true,
          "isSigner": true
        },
        {
          "name": "programTokenVault",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "programTokenVaultAuthority",
          "isMut": false,
          "isSigner": false
        },
        {
          "name": "recipientTokenAccount",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "tokenProgram",
          "isMut": false,
          "isSigner": false
        }
      ],
      "args": [
        {
          "name": "aProof",
          "type": {
            "vec": "u8"
          }
        },
        {
          "name": "bProof",
          "type": {
            "vec": "u8"
          }
        },
        {
          "name": "cProof",
          "type": {
            "vec": "u8"
          }
        },
        {
          "name": "publicInputs",
          "type": {
            "vec": "u64"
          }
        },
        {
          "name": "recipientAddress",
          "type": "publicKey"
        },
        {
          "name": "amountToWithdraw",
          "type": "u64"
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "ProgramState",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "admin",
            "type": "publicKey"
          },
          {
            "name": "tokenMint",
            "type": "publicKey"
          },
          {
            "name": "verifierProgramId",
            "type": "publicKey"
          },
          {
            "name": "bump",
            "type": "u8"
          },
          {
            "name": "whitelistedRelayers",
            "type": {
              "vec": "publicKey"
            }
          }
        ]
      }
    }
  ],
  "events": [
    {
      "name": "AdminChanged",
      "fields": [
        {
          "name": "oldAdmin",
          "type": "publicKey",
          "index": false
        },
        {
          "name": "newAdmin",
          "type": "publicKey",
          "index": false
        }
      ]
    },
    {
      "name": "RelayerAdded",
      "fields": [
        {
          "name": "relayerAddress",
          "type": "publicKey",
          "index": false
        }
      ]
    },
    {
      "name": "RelayerRemoved",
      "fields": [
        {
          "name": "relayerAddress",
          "type": "publicKey",
          "index": false
        }
      ]
    },
    {
      "name": "DepositOccurred",
      "fields": [
        {
          "name": "user",
          "type": "publicKey",
          "index": false
        },
        {
          "name": "tokenAddress",
          "type": "publicKey",
          "index": false
        },
        {
          "name": "amount",
          "type": "u64",
          "index": false
        },
        {
          "name": "commitment",
          "type": {
            "array": ["u8", 32]
          },
          "index": false
        }
      ]
    },
    {
      "name": "WithdrawalOccurred",
      "fields": [
        {
          "name": "nullifierHash",
          "type": {
            "array": ["u8", 32]
          },
          "index": false
        },
        {
          "name": "recipient",
          "type": "publicKey",
          "index": false
        },
        {
          "name": "tokenAddress",
          "type": "publicKey",
          "index": false
        },
        {
          "name": "amount",
          "type": "u64",
          "index": false
        }
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "AmountTooSmall",
      "msg": "Amount must be greater than zero."
    },
    {
      "code": 6001,
      "name": "InvalidPublicInputCount",
      "msg": "Invalid public input count for ZK proof."
    },
    {
      "code": 6002,
      "name": "RecipientMismatch",
      "msg": "Recipient mismatch in proof inputs."
    },
    {
      "code": 6003,
      "name": "AmountMismatch",
      "msg": "Amount mismatch in proof inputs."
    },
    {
      "code": 6004,
      "name": "InvalidZkProof",
      "msg": "Invalid ZK proof (placeholder check)."
    },
    {
      "code": 6005,
      "name": "RelayerAlreadyWhitelisted",
      "msg": "Relayer already whitelisted."
    },
    {
      "code": 6006,
      "name": "RelayerNotWhitelisted",
      "msg": "Relayer not whitelisted."
    },
    {
      "code": 6007,
      "name": "InvalidRelayerAddress",
      "msg": "Invalid relayer address."
    },
    {
      "code": 6008,
      "name": "NewAdminIsZero",
      "msg": "New admin cannot be the zero address (system program)."
    },
    {
      "code": 6009,
      "name": "Overflow",
      "msg": "Overflow during arithmetic operation."
    }
  ]
}; 