version: '3.8'

services:
  relayer:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount the entire codebase for development
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: uvicorn app.api:app --reload --host 0.0.0.0 --port 8000
    networks:
      - relayer-network

networks:
  relayer-network:
    driver: bridge 